services:
  tensorboard:
    image: tensorboard
    build: 
      context: .
      dockerfile: Dockerfile

    container_name: tensorboard
    ports:
      - "6006:6006"
    volumes:
      - ./logs:/logs
    command: tensorboard --logdir=/logs --bind_all